### ISSUE TITLE
The Leaflet module requires the main queue to be configured because it overrides `init`

### ISSUE THREAD

**Issue by PashaEfimchik** [pavel-corsaghin/react-native-leaflet#47]
I received the following warning log message:

The Leaflet module requires the main queue to be configured because it overrides `init` but does not implement `requiresMainQueueueSetup`. In a future release, React Native will default to initialising all native modules in the background thread unless explicitly forbidden.

I've been working with "expo":"~49.0.15", "react": "18.2.0.0", npm version 10.2.4 and tested on ios simulator.

How can this warning be fixed?
